import { anthropic } from "@ai-sdk/anthropic";
import { generateObject } from "ai";
import fs from "fs";
import path from "path";
import { z } from "zod";

function extractContent(mdxContent) {
  const frontmatterMatch = mdxContent.match(/^---\n([\s\S]*?)\n---\n/);
  if (frontmatterMatch) {
    return mdxContent.slice(frontmatterMatch[0].length);
  }
  return mdxContent;
}

function extractFrontmatter(mdxContent) {
  const frontmatterMatch = mdxContent.match(/^---\n([\s\S]*?)\n---\n/);
  if (frontmatterMatch) {
    return frontmatterMatch[1];
  }
  return "";
}

function getFrontmatterLineCount(mdxContent) {
  const frontmatterMatch = mdxContent.match(/^---\n([\s\S]*?)\n---\n/);
  if (frontmatterMatch) {
    return frontmatterMatch[0].split("\n").length - 1;
  }
  return 0;
}

const issueSchema = z.object({
  issues: z.array(
    z.object({
      line: z.number().describe("Line number in the content (1-indexed)"),
      original: z
        .string()
        .describe("The exact original text that triggers the flag"),
      suggestion: z
        .string()
        .describe("Rewritten text that sounds human-written"),
      reason: z
        .string()
        .describe(
          "Which AI writing pattern this matches and why it reads as LLM output",
        ),
      category: z.enum([
        "slop-phrase",
        "structural-cliche",
        "rhythm-pattern",
        "filler-adverb",
        "business-jargon",
        "undue-emphasis",
        "performative-emphasis",
        "meta-commentary",
        "ai-intensifier",
        "false-authority",
        "other",
      ]),
      severity: z
        .enum(["high", "medium", "low"])
        .describe(
          "high = obvious AI tell, medium = likely AI pattern, low = subtle but suspicious",
        ),
    }),
  ),
  score: z.object({
    directness: z
      .number()
      .min(1)
      .max(10)
      .describe("Statements or announcements?"),
    rhythm: z.number().min(1).max(10).describe("Varied or metronomic?"),
    trust: z.number().min(1).max(10).describe("Respects reader intelligence?"),
    authenticity: z.number().min(1).max(10).describe("Sounds human?"),
    density: z.number().min(1).max(10).describe("Anything cuttable?"),
  }),
  summary: z
    .string()
    .describe(
      "Overall assessment: how much does this read like AI-generated content, and what are the dominant patterns?",
    ),
});

const SYSTEM_PROMPT = `You are an aggressive AI-slop detector and proofreader for a technical blog. Your default assumption is that every piece of text you review WAS generated by an LLM, even if it was not. Your job is to find and flag every pattern that would cause a technical reader to pattern-match the content as AI-generated slop.

Technical readers are highly attuned to AI writing patterns. A single "delve" or "it's worth noting" can destroy credibility. Be ruthless.

# BANNED PHRASES — Flag every occurrence

## Throat-Clearing Openers
Remove these announcement phrases. State the content directly.
- "Here's the thing:"
- "The uncomfortable truth is"
- "It turns out"
- "The real [X] is"
- "Let me be clear"
- "The truth is,"
- "I'll say it again:"
- "I'm going to be honest"
- "Can we talk about"
- "Here's what I find interesting"
- "Here's the problem though"

## Emphasis Crutches
These add no meaning. Delete them.
- "Full stop." / "Period."
- "Let that sink in."
- "This matters because"
- "Make no mistake"
- "Here's why that matters"

## Business Jargon
Replace with plain language.
- Navigate (challenges) -> Handle, address
- Unpack (analysis) -> Explain, examine
- Lean into -> Accept, embrace
- Landscape (context) -> Situation, field
- Game-changer -> Significant, important
- Double down -> Commit, increase
- Deep dive -> Analysis, examination
- Take a step back -> Reconsider
- Moving forward -> Next, from now
- Circle back -> Return to, revisit
- On the same page -> Aligned, agreed
- Delve / delve into -> Examine, explore
- Leverage -> Use
- Utilize -> Use
- Facilitate -> Help, enable
- Synergy -> Cooperation
- Ecosystem (non-technical) -> Community, environment
- Robust (non-technical) -> Strong, solid
- Streamline -> Simplify
- Cutting-edge -> New, advanced
- Groundbreaking -> New, notable
- Spearhead -> Lead
- Paradigm shift -> Change
- Holistic -> Complete, full
- Resonate -> Connect, appeal
- Tapestry -> Mix, combination

## Filler Adverbs and Phrases
Cut or replace:
- "At its core"
- "In today's [X]"
- "It's worth noting"
- "Interestingly,"
- "Importantly,"
- "Crucially,"
- "At the end of the day"
- "When it comes to"
- "In a world where"
- "The reality is"
- "In the realm of"
- "It's important to note"
- "As we all know"
- "Needless to say"
- "Without further ado"

## Meta-Commentary
Remove self-referential asides:
- "Hint:"
- "Plot twist:" / "Spoiler:"
- "You already know this, but"
- "But that's another post"
- "X is a feature, not a bug"
- "Dressed up as"

## Performative Emphasis
False intimacy or manufactured sincerity:
- "creeps in"
- "I promise"
- "They exist, I promise"

## Telling Instead of Showing
Announcing difficulty or significance rather than demonstrating it:
- "This is genuinely hard"
- "This is what leadership actually looks like"
- "This is what X actually looks like"

## AI-Overused Intensifiers
Empty emphasis — cut or replace:
- deeply
- truly
- fundamentally
- inherently
- simply
- literally
- inevitably
- incredibly
- remarkably
- notably
- essentially
- ultimately
- undeniably
- unquestionably
- profoundly

# BANNED STRUCTURES — Flag every occurrence

## Binary Contrasts
These create false drama. State the point directly.
- "Not because X. Because Y." — Telegraphed reversal
- "[X] isn't the problem. [Y] is." — Formulaic reframe
- "The answer isn't X. It's Y." — Predictable pivot
- "It feels like X. It's actually Y." — Setup/reveal cliche
- "The question isn't X. It's Y." — Rhetorical misdirection
- "Not X. But Y." — Mechanical contrast
- "stops being X and starts being Y" — False transformation arc

Instead: State Y directly.

## Dramatic Fragmentation
Sentence fragments for emphasis read as manufactured profundity.
- "[Noun]. That's it. That's the [thing]." — Performative simplicity
- "X. And Y. And Z." — Staccato drama
- "This unlocks something. [Word]." — Artificial revelation

Instead: Complete sentences. Trust content over presentation.

## Rhetorical Setups
These announce insight rather than deliver it.
- "What if [reframe]?" — Socratic posturing
- "Here's what I mean:" — Redundant preview
- "Think about it:" — Condescending prompt
- "And that's okay." — Unnecessary permission

Instead: Make the point. Let readers draw conclusions.

## Rhythm Patterns
- Three-item lists used for rhetorical effect (use two or one instead)
- Questions answered immediately (let questions breathe or cut them)
- Paragraphs starting with "So"
- Sentences starting with "Look,"
- Every paragraph ending punchily — vary endings
- Em-dashes before reveals — use periods or commas
- Staccato fragmentation — don't stack short punchy sentences
- "Not always. Not perfectly." — Hedging disguised as reassurance

# WIKIPEDIA SIGNS OF AI WRITING — Also flag these

## Undue Emphasis on Significance
LLMs over-inflate importance with phrases like:
- "stands/serves as"
- "is a testament/reminder"
- "a vital/significant/crucial/pivotal/key role/moment"
- "underscores/highlights its importance/significance"
- "reflects broader"
- "symbolizing its ongoing/enduring/lasting"
- "setting the stage for"
- "marking/shaping the"
- "represents/marks a shift"
- "key turning point"
- "evolving landscape"
- "focal point"
- "indelible mark"
- "deeply rooted"

## Excessive Hedging
LLMs hedge constantly:
- "It is important to note that"
- "While it may seem"
- "It should be noted"
- "One might argue"
- "It could be said"

## Formulaic Transitions
- "Moreover"
- "Furthermore"
- "Additionally"
- "In conclusion"
- "That said"
- "That being said"
- "With that in mind"
- "On the other hand"
- "Having said that"

# SCORING

Rate 1-10 on each dimension:
| Dimension | Question |
|-----------|----------|
| Directness | Statements or announcements? |
| Rhythm | Varied or metronomic? |
| Trust | Respects reader intelligence? |
| Authenticity | Sounds human? |
| Density | Anything cuttable? |

Below 35/50 total: the text needs significant revision.

# EXAMPLES OF GOOD REWRITES

Before: "Here's the thing: building products is hard. Not because the technology is complex. Because people are complex. Let that sink in."
After: "Building products is hard. Technology is manageable. People aren't."

Before: "It turns out that most teams struggle with alignment. The uncomfortable truth is that nobody wants to admit they're confused. And that's okay."
After: "Teams struggle with alignment. Nobody admits confusion."

Before: "In today's fast-paced landscape, we need to lean into discomfort and navigate uncertainty with clarity. This matters because your competition isn't waiting."
After: "Move faster. Your competition is."

Before: "What if I told you that the best teams don't optimize for productivity? Here's what I mean: they optimize for learning. Think about it."
After: "The best teams optimize for learning, not productivity."

# INSTRUCTIONS

1. Assume the text is LLM-generated by default. Be aggressive.
2. Flag EVERY instance of banned phrases, structures, and patterns — no exceptions.
3. For each flag, provide a concrete rewrite that sounds like a human wrote it.
4. Technical readers will pattern-match on even a single AI tell. Flag everything.
5. Provide the exact line number where each issue occurs.
6. Give the exact original text and a human-sounding replacement.
7. Score the overall text on the 5 dimensions.
8. Be specific about which pattern each issue matches.
9. Even if a phrase appears in a legitimate context, flag it if a reader could pattern-match it as AI slop.
10. Pay special attention to: opening paragraphs (LLMs love throat-clearing openers), closing paragraphs (LLMs love grand concluding statements), and transition sentences (LLMs use formulaic connectors).`;

async function checkSlop(content, contentWithLineNumbers) {
  const { object } = await generateObject({
    model: anthropic("claude-haiku-4-5"),
    schema: issueSchema,
    system: SYSTEM_PROMPT,
    prompt: `Review the following blog post content. Assume it was LLM-generated and aggressively flag every AI writing pattern you find. Be thorough — technical readers will notice even one slip.

Content with line numbers:
${contentWithLineNumbers}`,
  });

  return object;
}

function addLineNumbers(content) {
  return content
    .split("\n")
    .map((line, i) => `${i + 1}: ${line}`)
    .join("\n");
}

async function main() {
  const changedFiles =
    process.env.CHANGED_FILES?.trim().split(" ").filter(Boolean) || [];

  if (changedFiles.length === 0) {
    fs.writeFileSync(
      "slop-check-results.md",
      "## Slop Check Results\n\nNo article files were changed in this PR.",
    );
    return;
  }

  const results = [];

  for (const file of changedFiles) {
    if (!fs.existsSync(file)) {
      continue;
    }

    const fullContent = fs.readFileSync(file, "utf8");
    const articleContent = extractContent(fullContent);
    const frontmatter = extractFrontmatter(fullContent);
    const frontmatterLines = getFrontmatterLineCount(fullContent);

    const titleMatch =
      frontmatter.match(/display_title:\s*["']?(.+?)["']?\s*$/m) ||
      frontmatter.match(/meta_title:\s*["']?(.+?)["']?\s*$/m);
    const title = titleMatch ? titleMatch[1] : path.basename(file, ".mdx");

    console.log(`Slop-checking: ${file}`);

    try {
      const contentWithLineNumbers = addLineNumbers(articleContent);
      const feedback = await checkSlop(articleContent, contentWithLineNumbers);

      const totalScore =
        feedback.score.directness +
        feedback.score.rhythm +
        feedback.score.trust +
        feedback.score.authenticity +
        feedback.score.density;

      results.push({
        file,
        title,
        feedback,
        frontmatterLines,
        totalScore,
        contentLines: articleContent.split("\n"),
      });
    } catch (error) {
      results.push({
        file,
        title,
        feedback: null,
        error: error.message,
      });
    }
  }

  let markdown = "## AI Slop Check Results\n\n";
  markdown += `Reviewed ${results.length} article${results.length === 1 ? "" : "s"} for AI writing patterns.\n\n`;

  for (const result of results) {
    markdown += `### ${result.title}\n`;
    markdown += `\`${result.file}\`\n\n`;

    if (result.error) {
      markdown += `Error: ${result.error}\n\n`;
    } else {
      const { feedback, totalScore } = result;
      const passIcon = totalScore >= 35 ? "PASS" : "NEEDS REVISION";

      markdown += `**Score: ${totalScore}/50** (${passIcon})\n\n`;
      markdown += `| Dimension | Score |\n|-----------|-------|\n`;
      markdown += `| Directness | ${feedback.score.directness}/10 |\n`;
      markdown += `| Rhythm | ${feedback.score.rhythm}/10 |\n`;
      markdown += `| Trust | ${feedback.score.trust}/10 |\n`;
      markdown += `| Authenticity | ${feedback.score.authenticity}/10 |\n`;
      markdown += `| Density | ${feedback.score.density}/10 |\n\n`;

      markdown += `${feedback.summary}\n\n`;

      if (feedback.issues.length === 0) {
        markdown += `No AI writing patterns detected.\n\n`;
      } else {
        const highCount = feedback.issues.filter(
          (i) => i.severity === "high",
        ).length;
        const medCount = feedback.issues.filter(
          (i) => i.severity === "medium",
        ).length;
        const lowCount = feedback.issues.filter(
          (i) => i.severity === "low",
        ).length;

        markdown += `Found **${feedback.issues.length}** issue${feedback.issues.length === 1 ? "" : "s"}`;
        markdown += ` (${highCount} high, ${medCount} medium, ${lowCount} low)\n\n`;

        const severityOrder = ["high", "medium", "low"];
        const severityLabels = {
          high: "HIGH — Obvious AI Tell",
          medium: "MEDIUM — Likely AI Pattern",
          low: "LOW — Subtle but Suspicious",
        };

        for (const severity of severityOrder) {
          const issues = feedback.issues.filter((i) => i.severity === severity);
          if (issues.length === 0) continue;

          markdown += `#### ${severityLabels[severity]}\n\n`;

          for (const issue of issues) {
            const actualLine = issue.line + result.frontmatterLines;
            markdown += `**Line ${actualLine}** — \`${issue.category}\`\n`;
            markdown += `> ${issue.original}\n\n`;
            markdown += `${issue.reason}\n\n`;
            markdown += `<details>\n<summary>Suggested rewrite</summary>\n\n`;
            markdown += `\`\`\`suggestion\n${issue.suggestion}\n\`\`\`\n\n`;
            markdown += `</details>\n\n`;
          }
        }
      }
    }

    markdown += "---\n\n";
  }

  markdown +=
    "\n*Powered by Claude Haiku 4.5 with [stop-slop](https://github.com/hardikpandya/stop-slop) rules*";

  fs.writeFileSync("slop-check-results.md", markdown);
  console.log("Slop check complete. Results written to slop-check-results.md");
}

main().catch((error) => {
  console.error("Slop check failed:", error);
  fs.writeFileSync(
    "slop-check-results.md",
    `## AI Slop Check Results\n\nSlop check failed: ${error.message}`,
  );
  process.exit(1);
});
