// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAllShortcuts() : Promise<ShortcutDef[]> {
    return await TAURI_INVOKE("plugin:shortcut|get_all_shortcuts");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ShortcutCategory = "Navigation" | "View" | "Tabs" | "Search" | "Editor"
export type ShortcutDef = { id: ShortcutId; keys: string; category: ShortcutCategory; description: string; scope: ShortcutScope }
export type ShortcutId = "new_note" | "new_empty_tab" | "close_tab" | "select_tab_1" | "select_tab_2" | "select_tab_3" | "select_tab_4" | "select_tab_5" | "select_tab_6" | "select_tab_7" | "select_tab_8" | "select_tab_9" | "prev_tab" | "next_tab" | "restore_closed_tab" | "open_calendar" | "open_contacts" | "open_ai_settings" | "open_folders" | "open_search" | "new_note_and_listen" | "toggle_chat" | "open_settings" | "toggle_sidebar" | "focus_search" | "open_note_dialog" | "switch_to_enhanced" | "switch_to_raw" | "switch_to_transcript" | "prev_panel_tab" | "next_panel_tab" | "transcript_search" | "undo_delete" | "dismiss" | "play_pause_audio"
export type ShortcutScope = "Global" | "Scoped"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
