use crate::types::{ShortcutCategory, ShortcutDef, ShortcutId, ShortcutScope};

pub fn all() -> Vec<ShortcutDef> {
    vec![
        ShortcutDef {
            id: ShortcutId::NewNote,
            keys: "mod+n".into(),
            category: ShortcutCategory::Tabs,
            description: "Create a new note".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::NewEmptyTab,
            keys: "mod+t".into(),
            category: ShortcutCategory::Tabs,
            description: "Open a new empty tab".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::CloseTab,
            keys: "mod+w".into(),
            category: ShortcutCategory::Tabs,
            description: "Close current tab".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::SelectTab1,
            keys: "mod+1".into(),
            category: ShortcutCategory::Tabs,
            description: "Switch to tab 1".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::SelectTab2,
            keys: "mod+2".into(),
            category: ShortcutCategory::Tabs,
            description: "Switch to tab 2".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::SelectTab3,
            keys: "mod+3".into(),
            category: ShortcutCategory::Tabs,
            description: "Switch to tab 3".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::SelectTab4,
            keys: "mod+4".into(),
            category: ShortcutCategory::Tabs,
            description: "Switch to tab 4".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::SelectTab5,
            keys: "mod+5".into(),
            category: ShortcutCategory::Tabs,
            description: "Switch to tab 5".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::SelectTab6,
            keys: "mod+6".into(),
            category: ShortcutCategory::Tabs,
            description: "Switch to tab 6".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::SelectTab7,
            keys: "mod+7".into(),
            category: ShortcutCategory::Tabs,
            description: "Switch to tab 7".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::SelectTab8,
            keys: "mod+8".into(),
            category: ShortcutCategory::Tabs,
            description: "Switch to tab 8".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::SelectTab9,
            keys: "mod+9".into(),
            category: ShortcutCategory::Tabs,
            description: "Switch to last tab".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::PrevTab,
            keys: "mod+alt+left".into(),
            category: ShortcutCategory::Navigation,
            description: "Switch to previous tab".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::NextTab,
            keys: "mod+alt+right".into(),
            category: ShortcutCategory::Navigation,
            description: "Switch to next tab".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::RestoreClosedTab,
            keys: "mod+shift+t".into(),
            category: ShortcutCategory::Tabs,
            description: "Restore last closed tab".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::OpenCalendar,
            keys: "mod+shift+c".into(),
            category: ShortcutCategory::Navigation,
            description: "Open calendar".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::OpenContacts,
            keys: "mod+shift+o".into(),
            category: ShortcutCategory::Navigation,
            description: "Open contacts".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::OpenAiSettings,
            keys: "mod+shift+comma".into(),
            category: ShortcutCategory::Navigation,
            description: "Open AI settings".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::OpenFolders,
            keys: "mod+shift+l".into(),
            category: ShortcutCategory::Navigation,
            description: "Open folders".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::OpenSearch,
            keys: "mod+shift+f".into(),
            category: ShortcutCategory::Search,
            description: "Open advanced search".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::NewNoteAndListen,
            keys: "mod+shift+n".into(),
            category: ShortcutCategory::Tabs,
            description: "Create a new note and start listening".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::ToggleChat,
            keys: "mod+j".into(),
            category: ShortcutCategory::View,
            description: "Toggle chat panel".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::OpenSettings,
            keys: "mod+,".into(),
            category: ShortcutCategory::Navigation,
            description: "Open settings".into(),
            scope: ShortcutScope::Global,
        },
        ShortcutDef {
            id: ShortcutId::ToggleSidebar,
            keys: "mod+\\".into(),
            category: ShortcutCategory::View,
            description: "Toggle sidebar".into(),
            scope: ShortcutScope::Scoped,
        },
        ShortcutDef {
            id: ShortcutId::FocusSearch,
            keys: "mod+k".into(),
            category: ShortcutCategory::Search,
            description: "Focus search input".into(),
            scope: ShortcutScope::Scoped,
        },
        ShortcutDef {
            id: ShortcutId::OpenNoteDialog,
            keys: "mod+o".into(),
            category: ShortcutCategory::Navigation,
            description: "Open note dialog".into(),
            scope: ShortcutScope::Scoped,
        },
        ShortcutDef {
            id: ShortcutId::SwitchToEnhanced,
            keys: "alt+s".into(),
            category: ShortcutCategory::Editor,
            description: "Switch to enhanced editor tab".into(),
            scope: ShortcutScope::Scoped,
        },
        ShortcutDef {
            id: ShortcutId::SwitchToRaw,
            keys: "alt+m".into(),
            category: ShortcutCategory::Editor,
            description: "Switch to raw editor tab".into(),
            scope: ShortcutScope::Scoped,
        },
        ShortcutDef {
            id: ShortcutId::SwitchToTranscript,
            keys: "alt+t".into(),
            category: ShortcutCategory::Editor,
            description: "Switch to transcript tab".into(),
            scope: ShortcutScope::Scoped,
        },
        ShortcutDef {
            id: ShortcutId::PrevPanelTab,
            keys: "ctrl+alt+left".into(),
            category: ShortcutCategory::Navigation,
            description: "Switch to previous panel tab".into(),
            scope: ShortcutScope::Scoped,
        },
        ShortcutDef {
            id: ShortcutId::NextPanelTab,
            keys: "ctrl+alt+right".into(),
            category: ShortcutCategory::Navigation,
            description: "Switch to next panel tab".into(),
            scope: ShortcutScope::Scoped,
        },
        ShortcutDef {
            id: ShortcutId::TranscriptSearch,
            keys: "mod+f".into(),
            category: ShortcutCategory::Search,
            description: "Search in transcript".into(),
            scope: ShortcutScope::Scoped,
        },
        ShortcutDef {
            id: ShortcutId::FindReplace,
            keys: "mod+h".into(),
            category: ShortcutCategory::Search,
            description: "Find and replace in note".into(),
            scope: ShortcutScope::Scoped,
        },
        ShortcutDef {
            id: ShortcutId::UndoDelete,
            keys: "mod+z".into(),
            category: ShortcutCategory::Tabs,
            description: "Undo delete".into(),
            scope: ShortcutScope::Scoped,
        },
        ShortcutDef {
            id: ShortcutId::Dismiss,
            keys: "esc".into(),
            category: ShortcutCategory::View,
            description: "Dismiss / close".into(),
            scope: ShortcutScope::Scoped,
        },
        ShortcutDef {
            id: ShortcutId::PlayPauseAudio,
            keys: "space".into(),
            category: ShortcutCategory::Editor,
            description: "Play or pause audio playback".into(),
            scope: ShortcutScope::Scoped,
        },
    ]
}
